export default [
    { id: 1, tags: ["Staff"] },
    {
      id: 2,
      pid: 1,
      tags: ["Staff"],
      company: "Razorpay",
      img: "https://www.w3schools.com/howto/img_avatar.png",
      name: "person1",
      tag: "@p1",
      rzp_id: 1,
    },
    {
      id: 3,
      pid: 1,
      tags: ["Staff"],
      company: "Razorpay",
      img: "https://d6xcmfyh68wv8.cloudfront.net/blog-content/uploads/2020/10/rzp-glyph-positive.png",
      name: "person2",
      tag: "@p2",
      rzp_id: 2,
    },
    {
      id: 4,
      pid: 1,
      tags: ["Staff"],
      company: "Razorpay",
      img: "https://d6xcmfyh68wv8.cloudfront.net/blog-content/uploads/2020/10/rzp-glyph-positive.png",
      name: "person3",
      tag: "@p3",
      rzp_id: 3,
    },
    {
      id: 5,
      pid: 1,
      tags: ["Staff"],
      company: "Razorpay",
      img: "https://d6xcmfyh68wv8.cloudfront.net/blog-content/uploads/2020/10/rzp-glyph-positive.png",
      name: "person4",
      tag: "@p4",
      rzp_id: 4,
    },
    {
      id: 6,
      pid: 1,
      tags: ["Staff"],
      company: "Razorpay",
      img: "https://d6xcmfyh68wv8.cloudfront.net/blog-content/uploads/2020/10/rzp-glyph-positive.png",
      name: "person5",
      tag: "@p5",
      rzp_id: 5,
    },
    {
      id: 7,
      pid: 3,
      tags: ["Staff"],
      company: "Razorpay",
      img: "https://d6xcmfyh68wv8.cloudfront.net/blog-content/uploads/2020/10/rzp-glyph-positive.png",
      name: "person6",
      tag: "@p6",
      rzp_id: 6,
    },
    {
      id: 8,
      pid: 1,
      tags: ["Staff"],
      company: "Razorpay",
      img: "https://d6xcmfyh68wv8.cloudfront.net/blog-content/uploads/2020/10/rzp-glyph-positive.png",
      name: "person7",
      tag: "@p7",
      rzp_id: 7,
    },
    {
      id: 9,
      pid: 1,
      tags: ["Staff"],
      company: "Razorpay",
      img: "https://d6xcmfyh68wv8.cloudfront.net/blog-content/uploads/2020/10/rzp-glyph-positive.png",
      name: "person8",
      tag: "@p8",
      rzp_id: 8,
    },
    {
      id: 10,
      pid: 1,
      tags: ["Staff"],
      company: "Razorpay",
      img: "https://d6xcmfyh68wv8.cloudfront.net/blog-content/uploads/2020/10/rzp-glyph-positive.png",
      name: "person9",
      tag: "@p9",
      rzp_id: 9,
    },
    { id: 11, pid: 5, tags: ["Department"], name: "New Department" },
    {
      id: 12,
      pid: 11,
      tags: ["Staff"],
      company: "Razorpay",
      img: "https://d6xcmfyh68wv8.cloudfront.net/blog-content/uploads/2020/10/rzp-glyph-positive.png",
      name: "person10",
      tag: "@p10",
      rzp_id: 10,
    },
    {
      id: 13,
      pid: 11,
      tags: ["Staff"],
      company: "Razorpay",
      img: "https://d6xcmfyh68wv8.cloudfront.net/blog-content/uploads/2020/10/rzp-glyph-positive.png",
      name: "person11",
      tag: "@p11",
      rzp_id: 11,
    },
  ];